# Generated by Django 6.0.3 on 2026-05-07 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_newsandevents_summary_es_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesters",
                to="core.session",
            ),
        ),
    ]
