# Generated by Django 6.0.3 on 2026-07-09 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_semester_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsandevents",
            name="media",
            field=models.FileField(
                default="news_events_media/news.png",
                upload_to="news_events_media/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
    ]
