# Generated by Django 6.0.3 on 2026-03-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_alter_essayquestion_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="choice_text_en",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="choice_text_es",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="choice_text_fr",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="choice_text_ru",
        ),
        migrations.RemoveField(
            model_name="question",
            name="content_en",
        ),
        migrations.RemoveField(
            model_name="question",
            name="content_es",
        ),
        migrations.RemoveField(
            model_name="question",
            name="content_fr",
        ),
        migrations.RemoveField(
            model_name="question",
            name="content_ru",
        ),
        migrations.RemoveField(
            model_name="question",
            name="explanation_en",
        ),
        migrations.RemoveField(
            model_name="question",
            name="explanation_es",
        ),
        migrations.RemoveField(
            model_name="question",
            name="explanation_fr",
        ),
        migrations.RemoveField(
            model_name="question",
            name="explanation_ru",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="description_es",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="description_fr",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="title_es",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="title_fr",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="title_ru",
        ),
    ]
