[program:blackboard-celery]
command=/home/django/blackboard/env/bin/celery -A core worker --loglevel=INFO  
directory=/home/django/blackboard/
user=django
numprocs=1
stdout_logfile=/home/django/blackboard/logs/celery.log
stderr_logfile=/home/django/blackboard/logs/celery.log
autostart=true
autorestart=true
startsecs=10

; Need to wait for currently executing tasks to finish at shutdown.
; Increase this if you have very long running tasks.
stopwaitsecs = 600

stopasgroup=true

; Set Celery priority higher than default (999)
; so, if rabbitmq is supervised, it will start first.
priority=1000

; Note: 
; Install supervisor before running the above command 
; # sudo apt-get install supervisor 
; move file to:: /etc/supervisor/conf.d/blackboard-celery.conf 
; then restart supervisor 
; sudo supervisorctl reread 
; sudo supervisorctl update 